import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Repertorio de Lucas",
  description: "Pagina de exercicio para desenvolvimento web  Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <meta
          charSet="utf-8" 
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
          description="Site de exercicio para pratica em HTML"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
